# .travis.yml
---
dist: xenial
sudo: required
language: python
python:
  - "3.6"
env:
  global:
    MONGODB_PACKAGE=mongodb-org
  jobs:
    MOLECULE_DISTRO=centos7
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=18_04-builded
  #   MONGODB_VERSION=4.2
  #   MONGODB_PACKAGE=mongodb-org
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=18_04-builded
  #   MONGODB_VERSION=4.0
  #   MONGODB_PACKAGE=mongodb-org
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=18_04-builded
  #   MONGODB_VERSION=3.6
  #   MONGODB_PACKAGE=mongodb
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=16_04-builded
  #   MONGODB_VERSION=4.2
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=16_04-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=16_04-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu
  #   DIST_VERSION=16_04-builded
  #   MONGODB_VERSION=3.4
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu-upstart
  #   DIST_VERSION=14_04-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu-upstart
  #   DIST_VERSION=14_04-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=ubuntu-upstart
  #   DIST_VERSION=14_04-builded
  #   MONGODB_VERSION=3.4
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=debian
  #   DIST_VERSION=9-builded
  #   MONGODB_VERSION=4.2
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=debian
  #   DIST_VERSION=9-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=debian
  #   DIST_VERSION=9-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=debian
  #   DIST_VERSION=8-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=debian
  #   DIST_VERSION=8-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=debian
  #   DIST_VERSION=8-builded
  #   MONGODB_VERSION=3.4
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=6-builded
  #   MONGODB_VERSION=4.2
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=6-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=6-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=6-builded
  #   MONGODB_VERSION=3.4
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=7-builded
  #   MONGODB_VERSION=4.2
  #   DOCKER_PRIVILEGED=false
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=7-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=false
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=7-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=false
  # - >
  #   DISTRIBUTION=centos
  #   DIST_VERSION=7-builded
  #   MONGODB_VERSION=3.4
  #   DOCKER_PRIVILEGED=false
  # - >
  #   DISTRIBUTION=amazonlinux
  #   DIST_VERSION=2-builded
  #   MONGODB_VERSION=4.2
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=amazonlinux
  #   DIST_VERSION=2-builded
  #   MONGODB_VERSION=4.0
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=amazonlinux
  #   DIST_VERSION=2-builded
  #   MONGODB_VERSION=3.6
  #   DOCKER_PRIVILEGED=true
  # - >
  #   DISTRIBUTION=amazonlinux
  #   DIST_VERSION=2-builded
  #   MONGODB_VERSION=3.4
  #   DOCKER_PRIVILEGED=true

services:
  - docker

install:
  - python3 -m pip install --upgrade pip
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "MongoDB 3.6"
      env:
        - MONGODB_VERSION=3.6
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - molecule test
        - AUTH_STATE=enabled molecule test
    - stage: "MongoDB 4.0"
      env:
        - MONGODB_VERSION=4.0
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - molecule test
        - AUTH_STATE=enabled molecule test
    - stage: "MongoDB 4.2"
      env:
        - MONGODB_VERSION=4.2
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - molecule test
        - AUTH_STATE=enabled molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
