---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Install prerequisite packages for molecule testing for Debian/Ubuntu >= 18
      apt:
        update_cache: true
        name:
          - gpg
          - dirmngr
      when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 18) or ansible_distribution == 'Debian'


