name: Amazon Linux 2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        molecule_distro:
          - amazonlinux2
        mongodb_version:
          - '4.2'
          - '4.0'
          - '3.6'
    env:
      MONGODB_VERSION: ${{ matrix.mongodb_version }}
      MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare tests
        run: pip install -r requirements.txt
      - name: Run default test
        run: molecule test
      - name: Run default test with enabled authentication
        run: AUTH_STATE=enabled molecule test
      - name: Run cluster test
        run: molecule test -s cluster
      - name: Run cluster test with enabled authentication
        run: AUTH_STATE=enabled molecule test -s cluster
