name: Test ansible role on Debian

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        molecule_distro: 
          - debian9
        mongodb_version:
          - '4.2'
          - '4.0'
          - '3.6'
    env:
      MONGODB_VERSION: ${{ matrix.mongodb_version }}
      MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare tests
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          molecule test
          AUTH_STATE=enabled molecule test
